package placeholder

import (
	"sort"
	"strings"
	"sync"
)

// ProviderPattern describes a secret pattern Veil can recognize and rewrite
// to a structurally-valid placeholder.
//
// Two registration styles share the same struct (collapsed from the
// pre-launch `Format` + `ProviderPattern` split). Set Match/Generate
// explicitly for hand-written providers whose detection or placeholder
// generation needs custom code (Supabase JWTs, multi-segment GitHub PATs,
// SendGrid's `SG.<22>.<43>` shape). Leave them nil and supply the
// declarative fields (Prefixes/KeyHints/Length/Charset) for the common
// "prefix + random body" case — `register` builds the matcher/generator
// from those fields.
//
// VaultEligible declares whether `veil init` may move a matched value out
// of .env and into the vault. Every provider that survives the launch
// cuts (all Bearer) sets it true; the field exists so a future provider
// whose auth flow can't be replayed with literal substitution (OAuth
// exchange, mTLS, HMAC) can leave it false — the credential is still
// detected by IsSecretLike but stays in cleartext.
type ProviderPattern struct {
	Name          string
	Hosts         []string
	VaultEligible bool

	// Explicit handlers — populated for hand-written providers and
	// auto-generated by `register` from the declarative fields below
	// when nil.
	Match    func(name, value string) bool
	Generate func(name, value string) string

	// Declarative fields used when Match/Generate are nil. Length=0
	// preserves the input value's length on Generate. Charset values:
	// "alphanumeric" (default), "hex", "base64", "upper-alphanumeric".
	Prefixes []string
	KeyHints []string
	Length   int
	Charset  string
}

// registry holds all registered provider patterns. Populated by the
// provider_*.go init() functions; iterated by Match/All/Names via the
// Registry wrapper.
var registry []ProviderPattern

// defaultSortMu serializes Registry rebuilds in DefaultRegistry. With the
// uniform priority tier (Phase 9 dropped the handwritten-vs-format split)
// the registry now iterates in registration order — but DefaultRegistry
// still hands out a defensive copy of the slice and the mutex guards that
// copy against a concurrent register().
var defaultSortMu sync.Mutex

// register adds a provider pattern to the default registry. When Match
// or Generate is nil, derives the handler from the declarative
// Prefixes / KeyHints / Length / Charset fields. The longest matching
// prefix wins on Generate, so callers can list shorter prefixes first
// without losing more-specific suffixes (e.g. ["sk-", "sk-ant-"]).
func register(p ProviderPattern) {
	if len(p.Prefixes) > 0 {
		// Sort prefixes by length descending so Match and Generate always
		// pick the longest matching prefix. Without this, callers who
		// register ["sk-", "sk-ant-"] see Generate produce "sk-..." losing
		// the "ant-" segment — a silent correctness bug.
		sorted := make([]string, len(p.Prefixes))
		copy(sorted, p.Prefixes)
		sort.SliceStable(sorted, func(i, j int) bool {
			return len(sorted[i]) > len(sorted[j])
		})
		p.Prefixes = sorted
	}
	if p.Match == nil {
		p.Match = declarativeMatcher(p)
	}
	if p.Generate == nil {
		p.Generate = declarativeGenerator(p)
	}
	registry = append(registry, p)
}

// declarativeMatcher builds a Match func from p's declarative fields:
// a value match against any of p.Prefixes, OR a case-insensitive name
// match against any of p.KeyHints.
func declarativeMatcher(p ProviderPattern) func(name, value string) bool {
	prefixes := p.Prefixes
	hints := p.KeyHints
	return func(name, value string) bool {
		for _, pfx := range prefixes {
			if strings.HasPrefix(value, pfx) {
				return true
			}
		}
		upper := strings.ToUpper(name)
		for _, h := range hints {
			if strings.Contains(upper, strings.ToUpper(h)) {
				return true
			}
		}
		return false
	}
}

// declarativeGenerator builds a Generate func from p's declarative fields:
// preserve the longest matching prefix, fill the remainder with random
// bytes from p.Charset, embed the sentinel at the start of the body.
func declarativeGenerator(p ProviderPattern) func(name, value string) string {
	prefixes := p.Prefixes
	length := p.Length
	charset := p.Charset
	return func(_, value string) string {
		prefix := ""
		for _, pfx := range prefixes {
			if strings.HasPrefix(value, pfx) {
				prefix = pfx
				break
			}
		}
		total := length
		if total == 0 {
			total = len(value)
		}
		rest := total - len(prefix)
		if rest < 0 {
			rest = 0
		}
		var body string
		switch charset {
		case "hex":
			body = randFromAlphabet(rest, "0123456789abcdef")
		case "base64":
			body = randBase64ish(rest)
		case "upper-alphanumeric":
			body = randUpperAlphanumeric(rest)
		default:
			body = randAlphanumeric(rest)
		}
		return sentinelize(prefix+body, len(prefix))
	}
}

// Registry holds a set of provider patterns. Use NewRegistry to construct an
// isolated registry for tests; DefaultRegistry returns a view over the
// package-level slice populated at init() time.
type Registry struct {
	patterns []ProviderPattern
}

// NewRegistry returns an empty Registry.
func NewRegistry() *Registry { return &Registry{} }

// Register appends a provider pattern. Match/Generate are derived from
// the declarative fields if nil — mirrors the package-level `register`.
func (r *Registry) Register(p ProviderPattern) {
	if len(p.Prefixes) > 0 {
		sorted := make([]string, len(p.Prefixes))
		copy(sorted, p.Prefixes)
		sort.SliceStable(sorted, func(i, j int) bool {
			return len(sorted[i]) > len(sorted[j])
		})
		p.Prefixes = sorted
	}
	if p.Match == nil {
		p.Match = declarativeMatcher(p)
	}
	if p.Generate == nil {
		p.Generate = declarativeGenerator(p)
	}
	r.patterns = append(r.patterns, p)
}

// Match returns the first provider whose Match returns true, or nil if none.
func (r *Registry) Match(name, value string) *ProviderPattern {
	for i := range r.patterns {
		if r.patterns[i].Match(name, value) {
			return &r.patterns[i]
		}
	}
	return nil
}

// Get returns the provider with the given name, or (zero, false).
func (r *Registry) Get(name string) (ProviderPattern, bool) {
	for _, p := range r.patterns {
		if p.Name == name {
			return p, true
		}
	}
	return ProviderPattern{}, false
}

// All returns the registered patterns in registration order. Callers must
// not append to or sort the returned slice.
func (r *Registry) All() []ProviderPattern {
	return r.patterns
}

// Names returns the names of all registered providers in registration
// order. Useful for contract tests that want to enumerate the registry
// without hard-coding a list.
func (r *Registry) Names() []string {
	out := make([]string, len(r.patterns))
	for i, p := range r.patterns {
		out[i] = p.Name
	}
	return out
}

// DefaultRegistry returns a Registry view over the package-level registry.
// The package-level defaultSortMu guards the snapshot copy against a
// concurrent register(); the returned wrapper holds a defensive copy of
// the slice so iteration on one wrapper can never race with a sort or
// append on the shared backing array.
//
// Each call returns a fresh wrapper so tests that mutate the package-
// level slice (e.g. `registry = registry[:before]`) still see the
// current state.
func DefaultRegistry() *Registry {
	defaultSortMu.Lock()
	snap := make([]ProviderPattern, len(registry))
	copy(snap, registry)
	defaultSortMu.Unlock()
	return &Registry{patterns: snap}
}
